#!/usr/bin/env python3
"""Generate GALLERY.md, an auto-updated index of every theme in the repo."""

from __future__ import annotations

import sys
import zipfile
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from themelib import read_manifest, theme_meta

THEMES_DIR = Path("themes")
OUT = Path("GALLERY.md")
GALLERY_URL = "https://themes.pelton.app"
PREVIEW_EXTS = (".png", ".webp", ".jpg", ".jpeg", ".gif", ".avif", ".svg")

START = "<!-- Generated by scripts/build_gallery.py. Do not edit by hand. -->"


def folder_preview(folder: Path) -> str | None:
    for ext in PREVIEW_EXTS:
        cand = folder / ("preview" + ext)
        if cand.exists():
            return f"{folder.as_posix()}/preview{ext}"
    return None


def ensure_folder_preview(folder: Path) -> None:
    if folder_preview(folder):
        return
    packs = sorted(folder.glob("*.peltontheme"))
    if not packs:
        return
    manifest = read_manifest(packs[0])
    if not manifest or not manifest.get("preview"):
        return
    inner = manifest["preview"]
    ext = Path(inner).suffix.lower()
    if ext not in PREVIEW_EXTS:
        return
    try:
        with zipfile.ZipFile(packs[0]) as zf:
            if inner in zf.namelist():
                (folder / f"preview{ext}").write_bytes(zf.read(inner))
    except zipfile.BadZipFile:
        pass


def theme_row(folder: Path) -> str | None:
    packs = sorted(folder.glob("*.peltontheme"))
    if not packs:
        return None
    meta = theme_meta(folder, packs)
    if not meta["flavors"]:
        return None

    name = meta["name"]
    author = ", ".join(meta["authors"]) or "—"
    bases = ", ".join(f"`{b}`" for b in meta["bases"]) or "—"
    version = f"`{meta['version']}`" if meta["version"] else "varies"
    made = f"`{meta['peltonMin']}`+" if meta["peltonMin"] else "—"
    license_id = ", ".join(f"`{lc}`" for lc in meta["licenses"]) or "—"

    preview = folder_preview(folder)
    if preview:
        cell = f'<a href="{folder.as_posix()}/"><img src="{preview}" width="220" alt="{name} preview"></a>'
    else:
        cell = "—"

    flavors = f" ({len(packs)} flavors)" if len(packs) > 1 else ""
    return (
        f"| {cell} "
        f"| [**{name}**]({folder.as_posix()}/){flavors} "
        f"| {author} "
        f"| {bases} "
        f"| {version} "
        f"| {made} "
        f"| {license_id} |"
    )


def render() -> str:
    rows = []
    if THEMES_DIR.is_dir():
        for folder in sorted(THEMES_DIR.iterdir()):
            if not folder.is_dir() or folder.name.startswith((".", "_")):
                continue
            row = theme_row(folder)
            if row:
                rows.append(row)

    count = len(rows)
    plural = "theme" if count == 1 else "themes"
    lines = [
        START,
        "",
        "# Theme gallery",
        "",
        f"**{count} {plural}.** Browse them live, with previews and one-click "
        f"download, at **[{GALLERY_URL.replace('https://', '')}]({GALLERY_URL})**.",
        "",
        "> [!NOTE]",
        "> This list is generated automatically from each theme's manifest when "
        "themes change. To add yours, see "
        "[CONTRIBUTING.md](CONTRIBUTING.md).",
        "",
    ]
    if rows:
        lines += [
            "| Preview | Theme | Author | Base | Version | Made for | License |",
            "| --- | --- | --- | --- | --- | --- | --- |",
            *rows,
        ]
    else:
        lines.append("_No themes yet. Be the first to [submit one](CONTRIBUTING.md)!_")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    if "--check" not in argv and THEMES_DIR.is_dir():
        for folder in sorted(THEMES_DIR.iterdir()):
            if folder.is_dir() and not folder.name.startswith((".", "_")):
                ensure_folder_preview(folder)
    new = render()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != new:
            print("GALLERY.md is out of date. Run scripts/build_gallery.py.")
            return 1
        print("GALLERY.md is up to date.")
        return 0
    OUT.write_text(new, encoding="utf-8")
    print(f"Wrote {OUT}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
