#!/usr/bin/env python3
"""Generate GALLERY.md, an index of every theme in the repository.

Runs in CI whenever themes change, so the gallery list stays in sync without
anyone editing it by hand. Data is read from each theme's ``.peltontheme``
manifest; preview thumbnails are shown when a theme ships a ``preview.*`` file
in its folder (a file GitHub can render, unlike one bundled inside the zip).

Usage:
    python3 scripts/build_gallery.py           # write GALLERY.md
    python3 scripts/build_gallery.py --check    # fail if GALLERY.md is stale

No third-party dependencies: standard library only.
"""

from __future__ import annotations

import json
import sys
import zipfile
from pathlib import Path

THEMES_DIR = Path("themes")
OUT = Path("GALLERY.md")
GALLERY_URL = "https://themes.pelton.app"
PREVIEW_EXTS = (".png", ".webp", ".jpg", ".jpeg", ".gif", ".avif", ".svg")

START = "<!-- Generated by scripts/build_gallery.py. Do not edit by hand. -->"


def read_manifest(pack: Path) -> dict | None:
    try:
        with zipfile.ZipFile(pack) as zf:
            if "manifest.json" not in zf.namelist():
                return None
            return json.loads(zf.read("manifest.json"))
    except (zipfile.BadZipFile, json.JSONDecodeError):
        return None


def folder_preview(folder: Path) -> str | None:
    for ext in PREVIEW_EXTS:
        cand = folder / ("preview" + ext)
        if cand.exists():
            return f"{folder.as_posix()}/preview{ext}"
    return None


def ensure_folder_preview(folder: Path) -> None:
    """Extract a bundled manifest preview into the folder so GitHub can show it.

    GALLERY.md is rendered by GitHub, which cannot read an image inside a zip.
    If the theme has no folder-level preview but its manifest bundles one, pull
    it out to ``preview.<ext>`` (committed by CI).
    """
    if folder_preview(folder):
        return
    packs = sorted(folder.glob("*.peltontheme"))
    if not packs:
        return
    manifest = read_manifest(packs[0])
    if not manifest or not manifest.get("preview"):
        return
    inner = manifest["preview"]
    ext = Path(inner).suffix.lower()
    if ext not in PREVIEW_EXTS:
        return
    try:
        with zipfile.ZipFile(packs[0]) as zf:
            if inner in zf.namelist():
                (folder / f"preview{ext}").write_bytes(zf.read(inner))
    except zipfile.BadZipFile:
        pass


def made_for(pel: dict) -> str:
    lo, hi = pel.get("min"), pel.get("max")
    if lo and hi:
        return f"`{lo}`–`{hi}`"
    if lo:
        return f"`{lo}`+"
    if hi:
        return f"≤ `{hi}`"
    return "—"


def theme_row(folder: Path) -> str | None:
    packs = sorted(folder.glob("*.peltontheme"))
    if not packs:
        return None
    manifest = read_manifest(packs[0])
    if manifest is None:
        return None

    slug = folder.name
    pel = manifest.get("pelton", {}) or {}
    name = manifest.get("name", slug)
    author = manifest.get("author", "—")
    version = manifest.get("version", "—")
    base = manifest.get("base", "—")
    license_id = manifest.get("license", "—")

    preview = folder_preview(folder)
    if preview:
        cell = f'<a href="{folder.as_posix()}/"><img src="{preview}" width="220" alt="{name} preview"></a>'
    else:
        cell = "—"

    flavors = f" ({len(packs)} flavors)" if len(packs) > 1 else ""
    return (
        f"| {cell} "
        f"| [**{name}**]({folder.as_posix()}/){flavors} "
        f"| {author} "
        f"| `{base}` "
        f"| `{version}` "
        f"| {made_for(pel)} "
        f"| `{license_id}` |"
    )


def render() -> str:
    rows = []
    if THEMES_DIR.is_dir():
        for folder in sorted(THEMES_DIR.iterdir()):
            if not folder.is_dir() or folder.name.startswith((".", "_")):
                continue
            row = theme_row(folder)
            if row:
                rows.append(row)

    count = len(rows)
    plural = "theme" if count == 1 else "themes"
    lines = [
        START,
        "",
        "# Theme gallery",
        "",
        f"**{count} {plural}.** Browse them live, with previews and one-click "
        f"download, at **[{GALLERY_URL.replace('https://', '')}]({GALLERY_URL})**.",
        "",
        "> [!NOTE]",
        "> This list is generated automatically from each theme's manifest when "
        "themes change. To add yours, see "
        "[CONTRIBUTING.md](CONTRIBUTING.md).",
        "",
    ]
    if rows:
        lines += [
            "| Preview | Theme | Author | Base | Version | Made for | License |",
            "| --- | --- | --- | --- | --- | --- | --- |",
            *rows,
        ]
    else:
        lines.append("_No themes yet. Be the first to [submit one](CONTRIBUTING.md)!_")
    return "\n".join(lines) + "\n"


def main(argv: list[str]) -> int:
    if "--check" not in argv and THEMES_DIR.is_dir():
        for folder in sorted(THEMES_DIR.iterdir()):
            if folder.is_dir() and not folder.name.startswith((".", "_")):
                ensure_folder_preview(folder)
    new = render()
    if "--check" in argv:
        current = OUT.read_text(encoding="utf-8") if OUT.exists() else ""
        if current != new:
            print("GALLERY.md is out of date. Run scripts/build_gallery.py.")
            return 1
        print("GALLERY.md is up to date.")
        return 0
    OUT.write_text(new, encoding="utf-8")
    print(f"Wrote {OUT} ({new.count(chr(10))} lines).")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
